---
title: "Getting Started with metalite.sl"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: true
    highlight: "textmate"
    css: "custom.css"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Getting Started with metalite.sl}
---

```{r}
library(metalite)
library(metalite.sl)
```

# Build a metadata
```{r}
adsl <- r2rtf::r2rtf_adsl
adsl$TRTA <- adsl$TRT01A
adsl$TRTA <- factor(adsl$TRTA,
  levels = c("Placebo", "Xanomeline Low Dose", "Xanomeline High Dose"),
  labels = c("Placebo", "Low Dose", "High Dose")
)

meta <- meta_adam(
  population = adsl,
  observation = adsl
) |>
  define_plan(plan = plan(
    analysis = "base_char", population = "apat",
    observation = "apat", parameter = "age;gender;race"
  )) |>
  define_population(
    name = "apat",
    group = "TRTA",
    subset = quote(SAFFL == "Y"),
    var = c("USUBJID", "TRTA", "SAFFL", "AGEGR1", "SEX", "RACE")
  ) |>
  define_observation(
    name = "apat",
    group = "TRTA",
    subset = quote(SAFFL == "Y"),
    var = c("USUBJID", "TRTA", "SAFFL", "AGEGR1", "SEX", "RACE")
  ) |>
  define_parameter(
    name = "age",
    var = "AGE",
    label = "Age (years)",
    vargroup = "AGEGR1"
  ) |>
  define_parameter(
    name = "gender",
    var = "SEX",
    label = "Gender"
  ) |>
  define_parameter(
    name = "race",
    var = "RACE",
    label = "Race"
  ) |>
  define_analysis(
    name = "base_char",
    title = "Participant Baseline Characteristics by Treatment Group",
    label = "baseline characteristic table"
  ) |>
  meta_build()
```

# Prepare the numbers

```{r}
outdata <- meta |>
  prepare_base_char(
    population = "apat",
    observation = "wk12",
    analysis = "base_char",
    parameter = "age;gender;race"
  )

outdata

outdata$n
outdata$char_n
outdata$char_var
outdata$char_prop
```

# Format the numbers

```{r}
outdata <- outdata |> format_base_char(display_col = c("n", "prop", "total"), digits_prop = 2)

outdata$tbl
```

```{r}
outdata <- outdata |> format_base_char(display_col = c("n", "prop"), digits_prop = 3)

outdata$tbl
```

# Output as RTF

```{r}
outdata |> rtf_base_char(
  source = "Source: [CDISCpilot: adam-adsl]",
  path_outdata = file.path(tempdir(), "base0char111.rtf"),
  path_outtable = tempfile(fileext = ".Rdata")
)
```
